apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
    name: music-3391a1
spec:
  alias: music
  serviceRef:
    apiGroup: bitnami.database.tanzu.vmware.com
    kind: RedisCluster
    name: music
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: redis-music
